### ISSUE TITLE
[Not A Bug] Might be interesting to you

### ISSUE THREAD

**Issue by SylvainDe** [mahanmarwat/that#6]
Hi,
I guess this might be interesting to you : http://stackoverflow.com/questions/101268/hidden-features-of-python#111176 .
Cheers.

**Comment by mahanmarwat** [comment]
@SylvainDe Splat operator (\* and **) has been already covered https://github.com/mahanmarwat/that#7-args-and-kwargs
Thank You,

**Comment by SylvainDe** [comment]
It was for all the answers and not the splat operator in particular but fair enough.

**Comment by mahanmarwat** [comment]
@SylvainDe I have been checked this long ago.
